console.log(document.querySelector(".container").innerHTML)
console.log(document.querySelector(".container").outerHTML)
console.log(document.querySelector(".container").innerText)
console.log(document.querySelector(".container").nodeName)
console.log(document.querySelector(".container").tagName)
console.log(document.querySelector(".container").textContent)
// document.querySelector(".box").hidden=true
document.querySelector(".box").innerHTML="Hey this is InnerHTML"
console.log(document.querySelector(".box").hasAttribute("style"))
document.querySelector(".box").setAttribute("style","color:red")
console.log(document.querySelector(".box").hasAttribute("style"))
console.log(document.querySelector(".box").getAttribute("style"))
document.querySelector(".box").removeAttribute("style")
console.log(document.querySelector(".box").attributes)
console.log(document.querySelector(".box").dataset)
let div=document.createElement("div")
div.innerHTML="I have been Inserted <b>by Sanket</b>"
div.setAttribute("class","created")
document.querySelector(".container").append(div)
// document.querySelector(".container").prepend(div)
// document.querySelector(".container").before(div)
// document.querySelector(".container").after(div)
// document.querySelector(".box").replaceWith(div)
let cont=document.querySelector(".container")
cont.insertAdjacentHTML("afterend","<b>I was Inserted</b>")
// cont.insertAdjacentHTML("beforeend","<b>I was Inserted</b>")
// cont.insertAdjacentHTML("afterbegin","<b>I was Inserted</b>")
// cont.insertAdjacentHTML("beforebegin","<b>I was Inserted</b>")
document.querySelector(".box").remove()
console.log(document.querySelector(".container").classList)
document.querySelector(".container").classList.add("added")
console.log(document.querySelector(".container").className)
document.querySelector(".container").classList.toggle("red")
document.querySelector(".container").classList.toggle("red")